### ISSUE TITLE
PF Version reporting

### ISSUE THREAD

**Issue by smithsg84** [parflow/parflow#101]
Add command line option to report PF version.  Like:

parflow -v

**Comment by kulkarni1** [comment]
would be interesting to have build number along with this? as of now we dont have any

**Comment by smithsg84** [comment]
What did you mean by "build number"?  

I have things setup to print the PF version, git commit checksum and compilation date.

parflow -v
Parflow version : v3.3.1-15-gb292400
Compiled on     : Feb  8 2019 10:57:05

**Comment by kulkarni1** [comment]
By build number I meant minor bug fixes in a current major release version. But looks like commit checksum and compilation date seems to achieve that, so my point is moot.

**Comment by smithsg84** [comment]
Fixed in pull #102
