### ISSUE TITLE
Tags 3.2.0, 3.1.7-beta, can't be compiled

### ISSUE THREAD

**Issue by surak** [parflow/parflow#115]
Steps:

```
- git clone ...
- git checkout tags/3.2.0
```

try and compile:

```
CMake Error: The source directory "[blabla]/parflow" does not appear to contain CMakeLists.txt.
```

Therefore they are useless as tags.

**Comment by smithsg84** [comment]
The older versions of Parflow only build with configure, CMake support was in v3.3.0

Use the configure script to build the older versions.
