### ISSUE TITLE
PFB CLM format documented incorrectly

### ISSUE THREAD

**Issue by vibraphone** [parflow/parflow#136]
There are 2 problems with section 6.3 of the ParFlow manual:
1. qflx_tran_veg is not listed in the fields written to `.C.pfb` files
2. The documentation seems to suggest the 22+ fields are interleaved when in fact they are recorded as separate k-index layers (meaning all values for one field are listed before any values for the next field). The manual seems to indicate all field values for a single (i,j) index are listed together.

**Comment by smithsg84** [comment]
Thanks for manual fixes.
