### ISSUE TITLE
Automatic Code Formatter

### ISSUE THREAD

**Issue by smithsg84** [parflow/parflow#15]
We should restart running Parflow through a code formatter as was previously done.

Current indentation is all over the map.

A format check should be part of the regression test so pull requests are verified to be correctly formatted.

Suggested tools are uncrustify or clang-format.

**Comment by kulkarni1** [comment]
Currently I use VIM and set the indentation to c. Any file can be auto indented by "=G" in command mode.

**Comment by fonseca-ins** [comment]
I like the uncrustify option, one can also add a git hook that checks if the  code is properly indented
when "git commit" is invoked and cancels the commit in case it isn't.

**Comment by smithsg84** [comment]
A new branch "fix-indent" has been created with uncrustify as the auto-formatter.   

A script to run formatter on all C code can be run with 

<at root of ParFlow source>
bin/pfformat 
Assuming uncrustify is installed.  https://github.com/uncrustify/uncrustify

The GNU style was used as the base since this style is supported by many editors and tools.  The GNU style was changed to NOT indent braces.  On other projects using GNU this part of the style is what most developers object to and ParFlow has not traditionally indented the braces.  E.G.
GNU style:
```
if (true)
  {
     printf("hello\n");
  }
```
Using this instead, with no indent on the braces:
```
if (true)
{
   printf("hello\n");
}
```

The big objection is adding extra horizontal white space.   

I'm open to just using GNU style as well.

@fonseca-ins Haven't done a commit hook yet but that would be a good next step.

**Comment by smithsg84** [comment]
Uncrustify code formatting has been committed to master.

bin/pfformat 

run from root of parflow source tree will reformat all .c and .h files.

**Comment by xy124** [comment]
I wrote a pre-commit hook. move this file into parflow/.git/hooks to test:
https://gist.github.com/xy124/c7274555655a315b07fa59da31ef0601
