### ISSUE TITLE
NefCDF output without MPI

### ISSUE THREAD

**Issue by jetuk** [parflow/parflow#164]
Is it possible to build a non-MPI version of Parflow with NetCDF support? I have tried through cmake but it seems there is a dependencies on `netcdf_par.h` even if sequential mode is enabled.

**Comment by kulkarni1** [comment]
Unfortunately not. Netcdf interface is for parallel io only. One can still
build everything with mpi and just run on single core.

**Comment by jetuk** [comment]
Thanks. This would still require execution using `mpiexec` or similar?

**Comment by kulkarni1** [comment]
yes. under linux it should be fairly straightforward

**Comment by jetuk** [comment]
Thanks for the answers. 

I'll close this issue now as I assume it's not something that will be supported going forward.
