### ISSUE TITLE
MPI_Comm_split passed invalid arguments

### ISSUE THREAD

**Issue by vibraphone** [parflow/parflow#197]
With openmpi 3.1.4 on Fedora 30, the call to `MPI_Comm_split(..., &amps_CommNode)` in `pfsimulator/amps/mpi1/amps_init.c` will sometimes fail ‒ whenever the `color` argument (the hash of the process name) is converted to a negative integer. This conversion is implicit since MPI_Comm_split takes an `int` argument but the hash is computed as a `uint32_t`.

**Comment by smithsg84** [comment]
Thanks for the bug report.   I made a change which I believe fixes using a new MPI-3 API.  Branch "bugfix/197-MPI_Comm_split".   Does this fix the bug?

https://github.com/parflow/parflow/tree/bugfix/197-MPI_Comm_split

**Comment by smithsg84** [comment]
Fixed in PR #202
