### ISSUE TITLE
Overland flow cell outflow

### ISSUE THREAD

**Issue by smithsg84** [parflow/parflow#232]
Currently overland flow output is available for outflow from the domain.   

Desired to have outflow from each cell rather than just along the boundary.

**Comment by smithsg84** [comment]
Summary of comments from Laura

- would be possible to have the flow output at a different frequency than the subsurface the way we do for clm?    I’m not sure how  hard that would be but I do think it might be common that people would want the overland flow written out at the same time interval as their CLM dumps but less frequently than the pressures.

- What you would be looking for is the ke_, kw_ etc that get passed back from the overland_eval module. Not the _der ones though, though should be the derivatives not the function I think. Ke_  should be equivalent to my qeast. But I think the dimensions of it are different and it doesn’t have the nx+1 because in this case we are calculating the kw too and I just did the east sides to avoid redundancies. Does that help? 

- Here is a link to the R function I wrote: https://github.com/lecondon/PriorityFlow/blob/master/Rpkg/R/CalcFlow.R

**Comment by smithsg84** [comment]
pftools  pfsurfacerunoff command is outdated, based on the old overland flow algorithm.   
This needs to be updated or just replaced.

**Comment by smithsg84** [comment]
I’m not sure where CLM dumps so would need to look at that.  If it is inside CLM Fortran code that would require a bit of work.
  
Writing the face fluxes as 2 files looks a bit hard since PF doesn’t have very generic support for NX+1, NY+1 data sizes.  Dumping the KE,KW,KN,KS as 2D vectors would be easy, this does duplicate values.  Pftools also might have some issue with NX+1, NY+1 datasets.

Would this cover needs?

1. Write KE,KW, KN, KS summed over output interval
   * Selectable output interval
      * PF interval
      * CLM interval (if reasonably easy to do)
2. Add pftools method to extract data from a 2D dataset on domain boundary
3. Create issues for future
   * Adding better support for non NX,NY,NZ data 2D/3D
            E.G. face data is N + 1.
    * Need to refactor output code
        * Make it more OO so we don’ have large sets of “if” logic all over
        * Add design pattern of a data manager?

**Comment by smithsg84** [comment]
Hi Steve, 

     

    Great here are my thoughts: 

     

    1. Yes writing KE, KN, KS, KW is a good way around the nx+1 ny+1 issue and would be fine with me, although this does make 4 more files so I guess it's really a question about whether we want the faces that much or not.  There are cases where the faces might be pretty important (i.e. for precise outflows along boundaries and potentially for dams too).  I hate to make it a flag: but I think that it should be an option either overlandFaces or just overland.  If you do regular overland it writes the outflow total for a grid cell and if you do faces it will write 4 files one for each face. 

     

     

    2. Unfortunately just summing KE, KW,  KN, KS all up will not get the desired result because that would be the net flux on every cell and what we are interested in is the outflow only so that’s why I have the checks in my script to only add fluxes when they are leaving a face.  When we write OverlandFlow per grid cell I think it should just be the outflow.

     

    3. Sorry I might have made that more confusing than it needs to be with the dump interval. I was just meaning that we could do something that would have the same effect as the CLM dump interval since that’s already an option in the tcl script. We could also specify an additional dump interval in the tcl scrip for overland flow?  Using the PF interval and the clm interval would be fine so we don’t have to add another interval. Or we could add a third interval which is the overland interval? 

     

    4.   Regardless if we have an overland interval which is > than the pf interval it would be important to sum up across time steps. Is that the summing you are talking about in your #1? 

     

    5. I like the idea of adding a pftool to extract data along a boundary separating that out seems like a logical approach to me.  In that case the boundary approach would be easy enough as long as we write face outflows but if we are doing the cell ones we would have to do an extra step to check that cells point out of the domain and not in.  Maybe we assume that if at least one face of a cell points out of the domain that we can use the total outflow and say its pointing out? 

     

    6. I agree with the issues you are leaving for the future here. And open to your thoughts on what of the things I’ve mentioned above should also be listed for future work. 

     

    Thanks, 

     

    Laura

**Comment by smithsg84** [comment]
I don’t think writing KE, etc  directly will work since the units are time dependent so can’t be ‘summed’.  The ‘outflow’ in Laura’s script is also a rate (? At least I think it is)  Units volume/t?

So the ‘summing’ method doesn’t work.   The existing overlandsum works because it is reporting a volume.

Or am I confused?

Should we save just the volume? Or ‘average’ flow like  (sum of volume over report interval) / (report interval) ?

**Comment by basileh** [comment]
Hello, thanks for the exchanges on this. 
0. I've coded Laura's R script in python, if needed. 
1. My point concerned the overlandsum that so far only works with the previous 'overlandFlow' option in the tcl, and not the new 'OverlandKinematics' option. This remains a pretty convenient output that conserves the budget while being written at PF dump rate. as Steve writes, this is summable.
2. I Did not thought about the face vs. cell issue. I reckon this can be pretty heavy but agree that a flag option would allow more flexibility
3. Concerning a specific output rate for the overland flow, I think the best option would be to have a specific dump interval, not necessarily linked to CLM, because you may want to run PF + overland without CLM. My own workaround (with CLM) is to include the surface pressure (which is being passed from CLM to PF) as a layer of a CLM 'C' file output: so I can typically have daily PF dumps and, say, 30mn CLM + surface pressure dumps, and then I recalculate fluxes using Laura's R, or my own python's script.
4. So this would leave 2 compatible options: 1 overlandsum (summable) at PF dump rate and 1 overlandflow 'snapshot' at a given dump rate which could be CLM's or not, and with either 4 arrays (KE, KW, KN, KS) or 1 (cell value). Do you think this is reasonable?
Best, Basile
