### ISSUE TITLE
Build issues when using the seq amps layer

### ISSUE THREAD

**Issue by vineetbansal** [parflow/parflow#240]
Hello,
I'm getting cmake build errors right off the bat (without changing any of the defaults except the install prefix), and using the default `seq` layer for amps. This looks to me to have do with the `pfsimulator/amps/seq` folder not being maintained w.r.t. the other layers.

For example:
https://github.com/parflow/parflow/blob/5e87b1602bc4daa4ae4aa255e3f25c748bfb4a2d/pfsimulator/amps/seq/amps.h#L380

This is a re-declaration of the very next line, and should be `AMPS_INVOICE_BYTE_CTYPE`.

Another example is:
https://github.com/parflow/parflow/blob/5e87b1602bc4daa4ae4aa255e3f25c748bfb4a2d/pfsimulator/amps/seq/amps.h#L383
which should be `4` instead of a `5`.

Another example:
https://github.com/parflow/parflow/blob/5e87b1602bc4daa4ae4aa255e3f25c748bfb4a2d/pfsimulator/amps/seq/amps.h#L367
`amps_Talloc` should be defined as `amps_TAlloc` instead.

And more errors down the line..

Being a new user, I'm wondering if it's worthwhile to bother with the `seq` layer (which I perhaps naively assumed would be the simplest option) or if I should go with the `mpi` layer, which did compile without any errors. In case it's not realistic to use `seq` further down the line for real datasets anyway, perhaps not worth the trouble?

**Comment by smithsg84** [comment]
Thanks for reporting the bug.   We do not currently regularly test the sequential version so it is not well maintained. 

MPI  is best supported option.
