### ISSUE TITLE
Install ParFlow without root permission

### ISSUE THREAD

**Issue by johnjarmitage** [parflow/parflow#242]
Hi, I am trying to install ParFlow on my work computer where I do not have root permissions. `cmake` builds the configuration without any issues, with the variable `PARFLOW_DIR` pointing to where the files are (once I saw that the sequential version has a bug and went for MPI). The `make` then runs fine, but `make install` wants to put libraries in `/lib`:
```
Install the project...
-- Install configuration: ""
-- Installing: /lib/libamps.a
CMake Error at pfsimulator/amps/cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/work/**myusername**/code/parflow/build/pfsimulator/amps/libamps.a" to
  "/lib/libamps.a".
Call Stack (most recent call first):
  pfsimulator/cmake_install.cmake:42 (include)
  cmake_install.cmake:42 (include)
```
Is there an option to get around this and put the libraries in a folder for which I have permissions?

Any advice would be really helpful.
John

**Comment by johnjarmitage** [comment]
Solved it:
I needed to use `-DCMAKE_INSTALL_PREFIX=$PARFLOW_DIR` not `-DCMAKE_INSTALL_PREFIX=$(PARFLOW_DIR)`

**Comment by smithsg84** [comment]
Thanks for reporting this, will fix $(variable) syntax in readme to avoid confusion.
