### ISSUE TITLE
Runs failing when computational grid not evenly divisible by processor topology

### ISSUE THREAD

**Issue by lecondon** [parflow/parflow#253]
ParFlow runs are failing when the computational grids nx, ny, nz is not evenly divisible by the processor topology p,q,r.  These issues are isolated to cases where (1) we are using a solid file and (2) we are using pfwritedb rather than pfrun.  Additional information: this has occurred with multiple domains on both Cori and Cheyenne, in all cases we are using terrain following grid, and variable dz and the computational grid thickness is set to match the solid file thickness exactly.

**Comment by smithsg84** [comment]
What does "failing" mean here? seg fault or some other fail??

Is there an example setup on cori somewhere?

**Comment by lecondon** [comment]
On Cheyenne which is were we have been testing lately we get an error saying: 'free(): invalid next size (fast):'

Jun Zhang just copied an example  of what we  have been running on Cori here: /global/cscratch1/sd/jzhang55/Amanda

There are two tests  there: 
1. pfidb_15lay.tcl / hrb_pfidb_rs - this is the parking lot test, it has a solid file and slope files
2. all_pfb_solid.tcl / hrb_pfidb_rs2 - this is the 3d domain with kfield, indicator, slopes and solid file

These were copied straight from Cheynne so the run script is what we were using there. We can update this if you need. 

Both of these work fine if we use pfrun to run but fail for pfwritedb unless the processor topology is set to 4,2,1

Let me know if we can provide anything else.

**Comment by smithsg84** [comment]
Hi Jun, Laura,

The directory is not visible, the group needs to be updated.

drwxr-x---  5 jzhang55 jzhang55        4096 Aug  5 16:34 Amanda_test

Steve

________________________________

**Comment by basileh** [comment]
Hey all,
i've got the same issue 'free(): invalid next size (fast):' 
A) on a run that's 100x100x15 cells and processor topology 4 x 4 x 1
topology 5 x 5 x 1 works fine. So that doesn t look like its related to the evenly division. 
Also: 1) there's a pfsol but 2) I'm using pfrun. I'm on a single node.

And 

B) on another cluster, I've got the same issue running a 250 x 250 x 15 cells domain, pfsol + pfrun:
- topology  5 x 5 x 1 works ok (requesting 1 node / 25 cores), 8 x 4 fails (requesting 1 node / 32 cores), 10 x 5 fails (requesting 2 nodes of 25 cores each), 8 x 8 fails (requesting 2 nodes / 32 cores each)
- more surprising: topology 2 x 25 (requesting 2 nodes of 25 cores each), WORKS while 25 x 2 FAILS 

hope this talks to someone !
Basile

**Comment by lecondon** [comment]
Hi Basile, 

Thanks for your reply. We have done some more testing and agree that the issue is not confined to cases where the processors don't divide evenly.  We are having the  same problem now with a processor topology of  32X32X1 on both Cori and Cheyenne. 

It looks like it may actually be related to the number of vertical layers.  If we reduce the number of vertical layers from 15 to 10 (still maintaining the same total thickness with the domain)  then the 32 by 32 topology works in both locations.  

Still not sure what is causing this, but it sounds like what we are seeing is consistent with you. 

Thanks, 

Laura

**Comment by kulkarni1** [comment]
Hi Laura and Basile,

If you enable the debug symbols and make parflow binary dump the core, you
should be able to analyze where the runs are failing with gdb. For advanced
usage, if Allinea's or TotalView's debugger is available, that should also
help.

Regards,
Ketan

**Comment by chekki2mo** [comment]
Hi all: 

Using gdb on the same exemple  of Basile ( 250 x 250 x 15 cells domain with 8 x 8 x 1 topology) leads to the following error with gdb 
=> line 173 of problem_real_space_z.c function which corresponds to a **tfree** command

Here is the entire traceback:

#5  0x00000000004ddd21 in realSpaceZ (problem_data=0x2, rsz=0x7fffffff5390)
    at /home/mchekki/LibGlace/src/outils/parflow/parflow-9c0b0f5/pfsimulator/parflow_lib/problem_real_space_z.c:173
#5  0x00000000004ddd21 in realSpaceZ (problem_data=0x2, rsz=0x7fffffff5390)
    at /home/mchekki/LibGlace/src/outils/parflow/parflow-9c0b0f5/pfsimulator/parflow_lib/problem_real_space_z.c:173
#6  0x000000000051740a in SetProblemData (problem_data=0x2)
    at /home/mchekki/LibGlace/src/outils/parflow/parflow-9c0b0f5/pfsimulator/parflow_lib/set_problem_data.c:141
#7  0x00000000004100c2 in SetupRichards (this_module=0x2)
    at /home/mchekki/LibGlace/src/outils/parflow/parflow-9c0b0f5/pfsimulator/parflow_lib/solver_richards.c:446
#8  0x0000000000418257 in SolverRichards ()
    at /home/mchekki/LibGlace/src/outils/parflow/parflow-9c0b0f5/pfsimulator/parflow_lib/solver_richards.c:5921
#6  0x000000000051740a in SetProblemData (problem_data=0x2)
    at /home/mchekki/LibGlace/src/outils/parflow/parflow-9c0b0f5/pfsimulator/parflow_lib/set_problem_data.c:141
#9  0x00000000004093fd in Solve ()
    at /home/mchekki/LibGlace/src/outils/parflow/parflow-9c0b0f5/pfsimulator/parflow_lib/solver.c:56
#7  0x00000000004100c2 in SetupRichards (this_module=0x2)
    at /home/mchekki/LibGlace/src/outils/parflow/parflow-9c0b0f5/pfsimulator/parflow_lib/solver_richards.c:446
#8  0x0000000000418257 in SolverRichards ()
    at /home/mchekki/LibGlace/src/outils/parflow/parflow-9c0b0f5/pfsimulator/parflow_lib/solver_richards.c:5921
#10 0x0000000000407c61 in main (argc=2, argv=0x7fffffff98f8)
    at /home/mchekki/LibGlace/src/outils/parflow/parflow-9c0b0f5/pfsimulator/parflow_exe/main.c:311
#9  0x00000000004093fd in Solve ()
    at /home/mchekki/LibGlace/src/outils/parflow/parflow-9c0b0f5/pfsimulator/parflow_lib/solver.c:56
#10 0x0000000000407c61 in main (argc=2, argv=0x7fffffff98f8)
    at /home/mchekki/LibGlace/src/outils/parflow/parflow-9c0b0f5/pfsimulator/parflow_exe/main.c:311

Bests
Mondher

**Comment by smithsg84** [comment]
Running with valgrind might point to the error, this is likely either multitple frees of same memory or memory corruption.

https://docs.nersc.gov/development/performance-debugging-tools/valgrind/

**Comment by smithsg84** [comment]
I tried a valgrind run on cori and we are seeing a huge number of warnings from valgrind on that platform which I don't see on other  systems.    So unfortunately valgrind may not help much on cori.

I'm running the

**Comment by smithsg84** [comment]
There appears to be an issue with valgrind and some Intel optimizations.    If you build with Release flags and Intel valgrind report a bunch of errors in the cJSON print methods.   This looks like the same issues as found in PETsc.

https://lists.mcs.anl.gov/pipermail/petsc-users/2012-December/015900.html

The cJSON valgrind warnings go away if GCC is used or if optimization is disabled on the Intel compiler.

**Comment by smithsg84** [comment]
Thanks for posting example; this should help with our debugging efforts.

Steve

________________________________

**Comment by smithsg84** [comment]
A patch has been pushed to master that fixes at one issue (hash 87b3217).  I'm able to run Basile's test case with 8x8x1 processor topology which was failing on a local machine.

More testing is needed.

**Comment by chekki2mo** [comment]
Hi all:
This patch works for me also for different topologies that failed without the patch. Many thanks.
I will continue doing more testing
Mondher

**Comment by lecondon** [comment]
Hi Steve, 

Thanks for the fix! We haven't been able to test Cori as it is down currently but this worked on Cheyenne and we are running again there. 

Laura

**Comment by smithsg84** [comment]
Closing old issue that was resolved.
