### ISSUE TITLE
Small incnsistency in README.md RE MPIEXEC

### ISSUE THREAD

**Issue by kgoergen** [parflow/parflow#268]
The README.md file advises to use -DMPIEXEC to set the MPI launcher at configure time. In fact it has to be MPIEXEC_EXECUTABLE, like -DMPIEXEC="/usr/bin/srun", otherwise parallel tests running 'make test' will fail.

**Comment by smithsg84** [comment]
Thanks for bug report.

The variable name returned/used by FINDMPI package changed at some point after CMake 3.9.
