### ISSUE TITLE
some information about interface conditions

### ISSUE THREAD

**Issue by pasquadambra** [parflow/parflow#276]
Hi,
could you give me information about the finite volume discretization of the 3D Richards' equation?
Which type of interface conditions are applied for discretizing the conductivity at the mid-point of volume faces? i.e., which type of average? Is there a reference to read fo a detailed discussion?
Thanks

**Comment by fonseca-ins** [comment]
Dear Pasqua,

A finite volume discretization is employed only for the overland flow component. The subsurface part is treated with
a cell centered finite differences method.  Regarding the conductivity, a Harmonic average is applied at cell interfaces. 
For more details please have a look at this publication  https://www.sciencedirect.com/science/article/abs/pii/S0309170814001894 and the references therein. 

Best regards,
Jose

**Comment by pasquadambra** [comment]
Thank you very much Jose! Best regards, Pasqua

 

Da: Jose A. Fonseca <notifications@github.com> 
Inviato: martedì 6 ottobre 2020 11:37
A: parflow/parflow <parflow@noreply.github.com>
Cc: pasquadambra <pasqua.dambra@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [parflow/parflow] some information about interface conditions (#276)

 

Dear Pasqua,

A finite volume discretization is employed only for the overland flow component. The subsurface part is treated with
a cell centered finite differences method. Regarding the conductivity, a Harmonic average is applied at cell interfaces.
For more details please have a look at this publication https://www.sciencedirect.com/science/article/abs/pii/S0309170814001894 and the references therein.

Best regards,
Jose
