### ISSUE TITLE
Serious bug in clm.F90 introduced in #264, 7bc1e62 

### ISSUE THREAD

**Issue by skollet** [parflow/parflow#282]
In clm.F90, the following code starting on line 569

if (slope_accounting_CLM==0) then
  	WHERE (slope_x_pf > 0)
  		slope_x_pf = 0
  		slope_y_pf = 0
  	ELSEWHERE 
  		slope_x_pf = 0
  		slope_x_pf = 0
  	END WHERE
  end if

results in flawed parflow results. Surprising that this actually passes the tests.

**Comment by reedmaxwell** [comment]
Looks like a PR to fix this right after this commit was never accepted?

https://github.com/parflow/parflow/commit/00c01b454273ea308fe8d5fd02df2c328549afeb

Please excuse the brevity of this message it was sent from my iPhone

On Oct 21, 2020, at 05:56, skollet <notifications@github.com> wrote:

﻿

In clm.F90, the following code starting on line 569

if (slope_accounting_CLM==0) then
WHERE (slope_x_pf > 0)
slope_x_pf = 0
slope_y_pf = 0
ELSEWHERE
slope_x_pf = 0
slope_x_pf = 0
END WHERE
end if

results in flawed parflow results. Surprising that this actually passes the tests.

**Comment by smithsg84** [comment]
I don't see a PR (other than Reed's new #283) that fixes this issue.

Just to document   

PR #264 introduced these lines.

PR #270 Added a change to loop to set slopes, line 465.   This looks correct to me:

      if (slope_accounting_CLM==1) then
      clm(t)%slope_x = slope_x_pf(ll)
      clm(t)%slope_y = slope_y_pf(ll)
      else
      clm(t)%slope_x = 0.0d0
      clm(t)%slope_y = 0.0d0
      end if
      end do ! t

**Comment by smithsg84** [comment]
Was fixed in #283
