### ISSUE TITLE
"amps-tests" are failing

### ISSUE THREAD

**Issue by Abdullah-Al-Fatta** [parflow/parflow#360]
I have installed ParFlow 3.9.0 in the HPC system of CU Boulder. I haven't got any issues when installing. But when I am running the test file from the 'build' folder using the command "make test", only 53% is passing. 50 tests out of 106 are failing. "amps-test1--1-1" to "amps-test10--1-1" and tcl files are passing and the following tests are failing. Can someone please tell me what could be the problem?

The following tests FAILED:

          9 - amps-test1-2-1 (Failed)
         10 - amps-test1-4-1 (Failed)
         11 - amps-test1-8-1 (Failed)
         12 - amps-test2-2-1 (Failed)
         13 - amps-test2-4-1 (Failed)
         14 - amps-test2-8-1 (Failed)
         15 - amps-test3-2-1 (Failed)
         16 - amps-test3-4-1 (Failed)
         17 - amps-test3-8-1 (Failed)
         18 - amps-test4-2-1 (Failed)
         19 - amps-test4-4-1 (Failed)
         20 - amps-test4-8-1 (Failed)
         21 - amps-test5-2-1 (Failed)
         22 - amps-test5-4-1 (Failed)
         23 - amps-test5-8-1 (Failed)
         24 - amps-test6-2-1 (Failed)
         25 - amps-test6-4-1 (Failed)
         26 - amps-test6-8-1 (Failed)
         27 - amps-test7-2-1 (Failed)
         28 - amps-test7-4-1 (Failed)
         29 - amps-test7-8-1 (Failed)
         30 - amps-test8-2-1 (Failed)
         31 - amps-test8-4-1 (Failed)
         32 - amps-test8-8-1 (Failed)
         33 - amps-test9-2-1 (Failed)
         34 - amps-test9-4-1 (Failed)
         35 - amps-test9-8-1 (Failed)
         36 - amps-test10-2-1 (Failed)
         37 - amps-test10-4-1 (Failed)
         38 - amps-test10-8-1 (Failed)
         39 - amps-test12-2-1 (Failed)
         40 - amps-test12-4-1 (Failed)
         41 - amps-test12-8-1 (Failed)
         42 - amps-test13-2-1 (Failed)
         43 - amps-test13-4-1 (Failed)
         44 - amps-test13-8-1 (Failed)
         45 - amps-test14-2-1 (Failed)
         46 - amps-test14-4-1 (Failed)
         47 - amps-test14-8-1 (Failed)
         48 - amps-test15-2-1 (Failed)
         49 - amps-test15-4-1 (Failed)
         50 - amps-test15-8-1 (Failed)
         51 - amps-test16-2-1 (Failed)
         52 - amps-test16-4-1 (Failed)
         53 - amps-test16-8-1 (Failed)
         54 - amps-test17-2-1 (Failed)
         55 - amps-test17-4-1 (Failed)
         56 - amps-test17-8-1 (Failed)
         84 - llnl-perm.tcl (Failed)
         86 - test_XPlusYPlusZ.tcl (Failed)
Errors while running CTest
make: *** [test] Error 8

**Comment by smithsg84** [comment]
What options are you giving to cmake to configure?  Are you trying to build a parallel version?

The 'amps' tests are tests of our MPI wrapper and those would indicate something is getting correctly configured for MPI.

When you run the cmake to configure are there any messages indicating MPI was found?   E.G. I get:

-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI_Fortran: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_usempif08.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")

**Comment by Abdullah-Al-Fatta** [comment]
Thank you for your response. I have used the following option to configure CMake:
cmake ../parflow \
>         -DCMAKE_INSTALL_PREFIX=${PARFLOW_DIR} \
>         -DPARFLOW_HAVE_CLM=ON \
>         -DPARFLOW_AMPS_LAYER=mpi1

I got similar messages as you mentioned after running cmake configuration. I am attaching the whole messages below:

-- The C compiler identification is Intel 17.0.4.20170411
-- The Fortran compiler identification is Intel 17.0.4.20170411
-- The CXX compiler identification is Intel 17.0.4.20170411
-- Check for working C compiler: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpicc
-- Check for working C compiler: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Fortran compiler: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpifc
-- Check for working Fortran compiler: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpifc  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpifc supports Fortran 90
-- Checking whether /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpifc supports Fortran 90 -- yes
-- Check for working CXX compiler: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpicxx
-- Check for working CXX compiler: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpicxx -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test FOUND
-- Performing Test FOUND - Success
Configuring version : v3.9.0
Using single file AMPS I/O for PFB output
-- Found MPI_C: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpicc (found version "3.1")
-- Found MPI_CXX: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpicxx (found version "3.1")
-- Found MPI_Fortran: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpifc (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Found Tclsh: /bin/tclsh (found version "8.5")
-- Performing Test FORTRAN_77_WORKS
-- Performing Test FORTRAN_77_WORKS - Success
-- Performing Test FORTRAN_F90_WORKS
-- Performing Test FORTRAN_F90_WORKS - Success
-- Performing Test HAVE_FC_ACCESS_STREAM
-- Performing Test HAVE_FC_ACCESS_STREAM - Success
-- Performing Test HAVE_FC_ACCESS_SEQUENTIAL
-- Performing Test HAVE_FC_ACCESS_SEQUENTIAL - Success
-- Checking Fortran implicit none flag : -implicitnone
-- Performing Test PARFLOW_FORTRAN_IMPLICIT_NONE_0
-- Performing Test PARFLOW_FORTRAN_IMPLICIT_NONE_0 - Success
-- Performing Test C_WORKS
-- Performing Test C_WORKS - Success
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for mallinfo
-- Looking for mallinfo - found
-- Configuring done
-- Generating done
-- Build files have been written to: /scratch/summit/aaf1@colostate.edu/parflow/build

**Comment by reedmaxwell** [comment]
Thanks for sending this.  How are you running the test auite?  On the head node or submitted as a parallel job or something else?

Please excuse the brevity of this message it was sent from my iPhone

On Aug 22, 2021, at 22:42, Abdullah Al Fatta ***@***.***> wrote:

﻿

Thank you for your response. I have used the following option to configure CMake:
cmake ../parflow \

    -DCMAKE_INSTALL_PREFIX=${PARFLOW_DIR} \
    -DPARFLOW_HAVE_CLM=ON \
    -DPARFLOW_AMPS_LAYER=mpi1


I got similar messages as you mentioned after running cmake configuration. I am attaching the whole messages below:

-- The C compiler identification is Intel 17.0.4.20170411
-- The Fortran compiler identification is Intel 17.0.4.20170411
-- The CXX compiler identification is Intel 17.0.4.20170411
-- Check for working C compiler: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpicc
-- Check for working C compiler: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Fortran compiler: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpifc
-- Check for working Fortran compiler: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpifc -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpifc supports Fortran 90
-- Checking whether /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpifc supports Fortran 90 -- yes
-- Check for working CXX compiler: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpicxx
-- Check for working CXX compiler: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpicxx -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test FOUND
-- Performing Test FOUND - Success
Configuring version : v3.9.0
Using single file AMPS I/O for PFB output
-- Found MPI_C: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpicc (found version "3.1")
-- Found MPI_CXX: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpicxx (found version "3.1")
-- Found MPI_Fortran: /curc/sw/intel/17.4/impi/2017.3.196/bin64/mpifc (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Found Tclsh: /bin/tclsh (found version "8.5")
-- Performing Test FORTRAN_77_WORKS
-- Performing Test FORTRAN_77_WORKS - Success
-- Performing Test FORTRAN_F90_WORKS
-- Performing Test FORTRAN_F90_WORKS - Success
-- Performing Test HAVE_FC_ACCESS_STREAM
-- Performing Test HAVE_FC_ACCESS_STREAM - Success
-- Performing Test HAVE_FC_ACCESS_SEQUENTIAL
-- Performing Test HAVE_FC_ACCESS_SEQUENTIAL - Success
-- Checking Fortran implicit none flag : -implicitnone
-- Performing Test PARFLOW_FORTRAN_IMPLICIT_NONE_0
-- Performing Test PARFLOW_FORTRAN_IMPLICIT_NONE_0 - Success
-- Performing Test C_WORKS
-- Performing Test C_WORKS - Success
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for mallinfo
-- Looking for mallinfo - found
-- Configuring done
-- Generating done
-- Build files have been written to: ***@***.***/parflow/build

**Comment by smithsg84** [comment]
Sorry about the problems.   Looks like it is finding MPI OK which is frequently a problem.   There might be something wrong with how what it being used to run MPI, do you know what the command should be?   srun, mpiexec, mpirun are frequently used.

If you go to the directory where built, you should be able to run a single test case and get more verbose output with:

ctest -V -R 'amps-test1-2-1'

This should show the command used to run the MPI test (the "Executing" line below, I'm using mpiexec) and the output.   The normal output from the AMPS tests is just "PASSED" for "FAILED"

> UpdateCTestConfiguration  from :/home/smithsg/projects/parflow/clean/pf-build/build/DartConfiguration.tcl
> Parse Config file:/home/smithsg/projects/parflow/clean/pf-build/build/DartConfiguration.tcl
> UpdateCTestConfiguration  from :/home/smithsg/projects/parflow/clean/pf-build/build/DartConfiguration.tcl
> Parse Config file:/home/smithsg/projects/parflow/clean/pf-build/build/DartConfiguration.tcl
> Test project /home/smithsg/projects/parflow/clean/pf-build/build
> Constructing a list of tests
> Done constructing a list of tests
> Updating test list for fixtures
> Added 0 tests to meet fixture requirements
> Checking test dependency graph...
> Checking test dependency graph end
> test 9
>     Start 9: amps-test1-2-1
> 
> 9: Test command: /home/smithsg/local/cmake/3.18.1/bin/cmake "-DPARFLOW_TEST=test1" "-DPARFLOW_RANKS=2" "-DPARFLOW_ARGS=1" "-DMPIEXEC=/usr/bin/mpiexec" "-DMPIEXEC_NUMPROC_FLAG=-n" "-DMPIEXEC_PREFLAGS=" "-DMPIEXEC_POSTFLAGS=--oversubscribe" "-P" "/home/smithsg/projects/parflow/clean/pf-build/parflow/cmake/modules/RunAmpsTest.cmake"
> 9: Test timeout computed to be: 1500
> 9: -- Executing: /usr/bin/mpiexec -n 2 --oversubscribe test1 1
> 9: -- Output:
> 9: PASSED
> 9: 
> 1/1 Test #9: amps-test1-2-1 ...................   Passed    0.50 sec
> 
> The following tests passed:
>         amps-test1-2-1
> 
> 100% tests passed, 0 tests failed out of 1
> 
> Total Test time (real) =   0.50 sec
> 
>

**Comment by Abdullah-Al-Fatta** [comment]
Thanks to both of you for your response. I am running on the head node, trying to test as submitting to the parallel job but not finding tcl file to run the amps test individually. I tried to find the 'amps-test' files using the command: 

grep -r '/scratch/summit/aaf1@colostate.edu/parflow' -e 'amps-test'

But I could not find the directory.

**Comment by Abdullah-Al-Fatta** [comment]
###This response was delayed because I thought there may be a compatibility issue with the Intel MPI and this test, so I have been trying to install ParFlow using OpenMPI. I reinstalled the ParFlow using the modules 'gcc/10.2.0' and 'openmpi/4.0.5'. I was using 'intel' and 'impi' modules previously. Now after running 'make test' from the build folder, 92% tests are passing. Only the following test is failing.

The following tests FAILED:
         67 - default_single.tcl_1_1_2 (Failed)
         68 - default_single.tcl_1_2_1 (Failed)
         69 - default_single.tcl_2_1_1 (Failed)
         70 - default_single.tcl_2_2_2 (Failed)
         71 - default_single.tcl_3_3_3 (Failed)
         72 - default_single.tcl_1_1_4 (Failed)
         73 - default_single.tcl_1_4_1 (Failed)
         74 - default_single.tcl_4_1_1 (Failed)
Errors while running CTest


### I got the following error when configuring CMake.

-- Performing Test HAVE_FC_ACCESS_SEQUENTIAL - Failed
-- Performing Test PARFLOW_FORTRAN_IMPLICIT_NONE_0 - Failed


### Moreover, I performed "ctest -V -R 'amps-test1-2-1' " and here is the more verbose output from the amps-test1-2-1, where it is using mpiexec.

UpdateCTestConfiguration  from :/projects/aaf1@colostate.edu/parflow3/build/DartConfiguration.tcl
Parse Config file:/projects/aaf1@colostate.edu/parflow3/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/projects/aaf1@colostate.edu/parflow3/build/DartConfiguration.tcl
Parse Config file:/projects/aaf1@colostate.edu/parflow3/build/DartConfiguration.tcl
Test project /projects/aaf1@colostate.edu/parflow3/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 9
    Start 9: amps-test1-2-1

9: Test command: /curc/sw/cmake/3.14.1/bin/cmake "-DPARFLOW_TEST=test1" "-DPARFLOW_RANKS=2" "-DPARFLOW_ARGS=1" "-DMPIEXEC=/curc/sw/openmpi/2.0.1/gcc/6.1.0/bin/mpiexec" "-DMPIEXEC_NUMPROC_FLAG=-n" "-DMPIEXEC_PREFLAGS=" "-DMPIEXEC_POSTFLAGS=" "-P" "/projects/aaf1@colostate.edu/parflow3/parflow/cmake/modules/RunAmpsTest.cmake"
9: Test timeout computed to be: 1500
9: -- Executing: /curc/sw/openmpi/2.0.1/gcc/6.1.0/bin/mpiexec -n 2 test1 1
9: -- Output:
9: Node 0: Node 0: number procs = 2
9: Node 0: arg[1] = 1
9: Node 1: Node 1: number procs = 2
9: Node 1: arg[1] = 1
9: PASSED
9:
1/1 Test #9: amps-test1-2-1 ...................   Passed    0.35 sec

The following tests passed:
        amps-test1-2-1

100% tests passed, 0 tests failed out of 1
