### ISSUE TITLE
Input database value buffer is too small

### ISSUE THREAD

**Issue by alanquits** [parflow/parflow#374]
The maximum length of a value in the input database is set to 4096 characters. This is enough space for most applications, but I have exceeded it. This can happen in string arrays when several hundred meaningful names are used. I exceeded it with well names. 

I think the best way to deal with this issue is to dynamically size the database value. Other options, in order of decreasing personal preference are:
 
- Increase the maximum length by a factor of 2 or 4 so it happens less frequently. This would require a little more memory usage and is just delaying this from happening again to someone else.
- Keep the maximum length at 4096 and add a bounds check when the input database is read that emits a meaningful error asking the user to edit and recompile. This would still be a hassle for the user, but it's less of a hassle than tracking down the error first.
- Do nothing. It's not a very common occurrence, but segfaults are awful things.

I'm happy to implement any of these changes and submit a pull request (maybe in an upcoming weekend), but I wanted to see if anyone else had an opinion on the matter first.

**Comment by smithsg84** [comment]
Size of the buffer was changed in #378
