### ISSUE TITLE
CMake Python version does not necessarily support f-strings

### ISSUE THREAD

**Issue by alanquits** [parflow/parflow#376]
CMakeLists.txt appears to be looking for a Python version compatible with 3.3, but parts of the ParFlow Python source code use f-strings, which were not implemented until version 3.6. 

I personally like the older c-style string formatting with wider compatibility, but since f-strings are easy to look at and already appear in several places in the ParFlow code base, it's probably easier to update CMakeLists.txt.

**Comment by smithsg84** [comment]
Thanks for the bug report, I updated CMake to Python 3.6
