### ISSUE TITLE
Error: Invalid value <FullJacobian> for key <Solver.Linear.Preconditioner.PFMGOctree>

### ISSUE THREAD

**Issue by jsacerot** [parflow/parflow#417]
I just installed ParFlow v3.11 on a CentOS machine and ran test example ```LW_Test.tcl```. I got an error associated with Hypre. Any ideas on how to fix it?

Output on cmd:
```
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
child process exited abnormally
    while executing
"exec sh /home/jsat/ParFlow-3.11/parflow/bin/run LW 1"
    ("eval" body line 1)
    invoked from within
"eval exec sh $Parflow::PARFLOW_DIR/bin/run  $runname $NumProcs"
    invoked from within
"if [pfexists Process.Command] {
        set command [pfget Process.Command]
        puts [format "Using command : %s" [format $command $NumProcs $runname]]
        puts [e..."
    (procedure "pfrun" line 53)
    invoked from within
"pfrun    $runname"
    (file "LW_Test.tcl" line 517)
```
Log records in ```LW.out.txt```:

```
Node 0: Error: Invalid value <FullJacobian> for key <Solver.Linear.Preconditioner.PFMGOctree>.
Hypre PFMG code not compiled in.
```

Thank you!

**Comment by jsacerot** [comment]
@reedmaxwell, thank you for your prompt reply. I have been following the wiki instructions but using the available compilers (Intel 2018.1.163 & mvapich2-2.2-psm) on the cluster I have access to (no admin privileges). Effectively, there is an issue with the Hypre installation. Are there any restrictions on ParFlow regarding libraries version?

**Comment by smithsg84** [comment]
The hypre version used in our testing is v2.18.2.    It could be newer Hypre versions have changed something that will require us to update our use of Hypre.   I created a separate issue for the Hypre version problem #418

Until we update hypre you could install it locally (hypre does not require admin access to install)


   if [ ! v2.18.2.tar.gz ]
   then
      wget https://github.com/hypre-space/hypre/archive/v2.18.2.tar.gz
   fi

   tar xf v2.18.2.tar.gz 

   pushd hypre-2.18.2/src

   CC=cc ./configure --prefix=${PARFLOW_HYPRE_DIR}
   make 
   make install

And specify this older hypre directory when running cmake to setup ParFlow:

	-DHYPRE_ROOT=${PARFLOW_HYPRE_DIR}

**Comment by jsacerot** [comment]
@smithsg84 @reedmaxwell I reported the problem with the Hypre 2.25.0 installation as an [issue](https://github.com/hypre-space/hypre/issues/746) on their repository and was able to install it properly. Now the ParFlow ```LW_Test.tcl``` runs but the validation fails (See log below). Any ideas? Do you think the problem is associated with the Hypre version? 

```
tclsh LW_Test.tcl
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)
Using process grid (1,1,1)

ParFlow run Complete
FAILED : Max difference in LW.out.eflx_lh_tot.00012.pfb
        Minimum significant digits at ( 38,   0,   0) =  0
        Correct value 2.230040e-01
        Computed value 0.000000e+00
        Difference 2.230040e-01
        Maximum absolute difference = 7.836590e-01
FAILED : Max difference in LW.out.qflx_evap_soi.00012.pfb
        Minimum significant digits at ( 38,   0,   0) =  0
        Correct value 8.883207e-08
        Computed value 0.000000e+00
        Difference 8.883207e-08
        Maximum absolute difference = 3.117527e-07
FAILED : Max difference in LW.out.qflx_evap_tot.00012.pfb
        Minimum significant digits at ( 38,   0,   0) =  0
        Correct value 8.883207e-08
        Computed value 0.000000e+00
        Difference 8.883207e-08
        Maximum absolute difference = 3.121650e-07
FAILED : Max difference in LW.out.t_grnd.00012.pfb
        Minimum significant digits at (  3,  26,   0) =  3
        Correct value 2.980464e+02
        Computed value 2.980167e+02
        Difference 2.975310e-02
        Maximum absolute difference = 2.975310e-02
FAILED : Max difference in LW.out.eflx_sh_tot.00012.pfb
        Minimum significant digits at (  3,  26,   0) =  2
        Correct value 4.243993e+02
        Computed value 4.241118e+02
        Difference 2.875405e-01
        Maximum absolute difference = 2.875405e-01
FAILED : Max difference in LW.out.qflx_evap_veg.00012.pfb
        Minimum significant digits at (  3,  26,   0) =  3
        Correct value 2.318861e-05
        Computed value 2.317961e-05
        Difference 8.997292e-09
        Maximum absolute difference = 9.040340e-09
FAILED : Max difference in LW.out.t_soil.00012.pfb
        Minimum significant digits at (  3,  26,   9) =  3
        Correct value 2.980464e+02
        Computed value 2.980167e+02
        Difference 2.975310e-02
        Maximum absolute difference = 2.975310e-02
FAILED : Max difference in LW.out.eflx_soil_grnd.00012.pfb
        Minimum significant digits at (  0,  26,   0) =  0
        Correct value -1.567692e-01
        Computed value 2.237375e-01
        Difference 3.805067e-01
        Maximum absolute difference = 7.918272e-01
FAILED : Max difference in LW.out.qflx_infl.00012.pfb
        Minimum significant digits at ( 38,   0,   0) =  0
        Correct value -8.883207e-08
        Computed value 0.000000e+00
        Difference 8.883207e-08
        Maximum absolute difference = 3.117527e-07
FAILED : Max difference in LW.out.qflx_evap_grnd.00012.pfb
        Minimum significant digits at ( 38,   0,   0) =  0
        Correct value 8.883207e-08
        Computed value 0.000000e+00
        Difference 8.883207e-08
        Maximum absolute difference = 3.117527e-07
FAILED : Max difference in LW.out.qflx_tran_veg.00012.pfb
        Minimum significant digits at (  3,  26,   0) =  3
        Correct value 2.318861e-05
        Computed value 2.317961e-05
        Difference 8.997292e-09
        Maximum absolute difference = 9.040340e-09
default_single : FAILED
```

**Comment by smithsg84** [comment]
@jsacerot Sorry the Hypre compile suggestion I initially wrote was wrong, I copied this from the build for the NERSC Cori machine which does things differently so "cc' is used to compile MPI programs.   Using mpicc as suggested is the correct thing to do.

**Comment by smithsg84** [comment]
Those differences do look like something is wrong, there are some zero fields being written.    We might expect some differences due to solver changes but not as large as this.

I'll try hypre 2.25.0 locally to see what the tests look like locally.

**Comment by smithsg84** [comment]
I get the same result on my local machine as well BUT it is not a hypre issue.   Do to a bug in the testing script it was not correctly reporting a failure on the Washita test and this result also occurs with the hypre 2.18.2.

There was a change in commit 6af282517  that caused the results to change.   

> commit b99098ffd723e30d3c405981e4c70dd1c287d5cc FAILED
> commit 6af282517fbdc1880a38de686f8e8e120b60d627 FAILED
> commit 968f722d37432ed6ef15461e223f261dfcaadf92 PASSED
> commit e75a3f16b89be01cb7f5fe1a251a9383c9992273 PASSED
> 

```
git checkout 968f722d37432ed6ef15461e223f261dfcaadf92
# build parflow
cd parflow/test/tcl/washita/tcl_scripts
tclsh LW_Test.tcl

```
@reedmaxwell This is the CLM fix from Sep 16th:

`    Fixed an issue that was identified by @danielletijerina where some bare soil on vegetated surfaces wasn't being beta-limited in CLM. Fixes to clm_thermal.F90 were implemented. At the same time, CLM snow additions and dew corrections by LBearup were added. A snow-age fix for deep snow was implemented along with canopy dew.`
    
This changed the LW results but the new results could be correct.  Was the bug you fixed showing up in LW and we should update regression results?

**Comment by smithsg84** [comment]
I will update the test to fix the false reporting of passing when it is not passing.

@jsacerot Thanks for reporting this!

**Comment by jsacerot** [comment]
@smithsg84, thanks to you for the technical support. Should I wait until you update the test or can I assume that my ParFlow installation is fully functional?

**Comment by smithsg84** [comment]
@jsacerot The LW test should be working again with the latest commit to PF.   The regression test output needed to be updated; the code was not changed.

The CI was fixed to correctly report that the test is failing so getting things out of sync should hopefully not happen again.

Thanks for reporting this.

**Comment by jsacerot** [comment]
@smithsg84, for your records, ```LW_Test.tcl``` and ```LW_Timing.tcl``` tests passed on my side too.

Cheers!
