### ISSUE TITLE
Hypre version compatiblity

### ISSUE THREAD

**Issue by smithsg84** [parflow/parflow#418]
Hypre version 2.25.0 reportedly (see #417) has problems with ParFlow.

For reference 2.18.2 is currently the Hypre version used in testing.

**Comment by smithsg84** [comment]
Tests are running with hypre 2.25.0.   The real problem is  #419 and the LW_Test test began failing with commit  6af282517fbdc1880a38de686f8e8e120b60d627 but was not detected at that time.

**Comment by jsacerot** [comment]
@smithsg84, just letting you know that Hypre 2.26.0 was recently released and that ParFlow 3.11 installation fails using it.

**Comment by smithsg84** [comment]
Version 2.26.0 is working locally and in our test suite.   I have just updated the CI build to use 2.26.0.

What error are you seeing?

**Comment by jsacerot** [comment]
@smithsg84 sorry for my late reply. My supervisor got the error but never provided the evidence. I just tried to upgrade my ParFlow from v.3.11 to v.3.12 using ```hypre v.26.0``` and faced the same issue:

```
/usr/bin/ld: /home/jsat/ParFlow-3.12/hypre-2.26.0/lib/libHYPRE.a(box.o): undefined reference to symbol '_intel_fast_memset'
```
Here are the [ParFlow_install.log](https://github.com/parflow/parflow/files/10680819/ParFlow_install.log) and [Hypre_install.log](https://github.com/parflow/parflow/files/10680825/Hypre_install.log) in case you need to verify some detailed info.

Thank you!

**Comment by jsacerot** [comment]
@smithsg84 Got the same error using ```hypre v.2.25.0```.  Not sure if the issue has to do with a requirement that my machine does not fulfill.

**Comment by smithsg84** [comment]
It looks like the GNU CC compiler is being used to compile ParFlow:

```
 The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
```
And Intel is used to compile Hyper:

`/act/mvapich2-2.2-psm/intel/bin//mpicc accepts -g... yes`

You could try compiling Parflow using the same compiler as hyper:

CC=mpicc CXX=mpiCC FC=mpif90 cmake ....

**Comment by smithsg84** [comment]
Also your ParFlow log has:

```
Manually-specified variables were not used by the project:

    PARFLOW_AMPS_SEQUENTIAL_OI
```
I think there is a typo on your cmake arguments, should be "IO" not "OI".

**Comment by jsacerot** [comment]
Thank you, @smithsg84. Last time my system identified the compilers correctly. I explicitly specified them as you suggested, and the installation was successful.

**Comment by smithsg84** [comment]
Ideally this should't be an issue with C code but some of the Intel optimizations seem to require specialized libraries.
