### ISSUE TITLE
Invalid type <PFBfile> for keys <Geom.domain.Porosity.Type> and <Mannings.Type>

### ISSUE THREAD

**Issue by jsacerot** [parflow/parflow#422]
@reedmaxwell  @smithsg84, the following input keys generate an error when reading in porosity and Manning's roughness values from PFB files.

1) Porosity :
```
pfset Geom.Porosity.GeomNames    "domain"
pfset Geom.domain.Porosity.Type    "PFBfile"    ; # input key for type PFBfile appears at input_porosity.c but no in manual
pfset Geom.domain.Porosity.FileName    $env(PFBfiles_DIR)/KWHM_PR.pfb
```
```Error: invalid porosity type <PFBfile> for key <Geom.domain.Porosity.Type>```

2) Manning :
```
pfset Mannings.GeomNames    "domain"
pfset Mannings.Type    "PFBfile"
pfset Mannings.FileName    $env(PFBfiles_DIR)/KWHM_MN_d.pfb
```
```Error: invalid type <PFBfile> for key <Geom.domain.SpecificStorage.Value>```
Notice that the Manning keys are generating an error associated with Specific Storage, which was assigned a constant value as there is no input key to read in from a PFBfile (See [issue #391](https://github.com/parflow/parflow/issues/391)). There may be a bug in the code or an error in the error message.

I temporarily skip the problem by assigning constant values to both variables while the issue is evaluated and fixed by ParFlow developers.

--------------------------------------------------------------------------------------------------------------------------------------
For your records, here are the input keys for specific storage :
```
pfset SpecificStorage.GeomNames   "domain"
pfset SpecificStorage.Type    "Constant"
pfset Geom.domain.SpecificStorage.Value   1.0e-5
```

**Comment by jsacerot** [comment]
For Porosity, Type PFBfile is missing in ```parflow-master\pf-keys\definitions\geom.yaml```. It should be something like this:
```
xxx              - PFBfile
```
After line 815:
```
815              - Constant
```

@smithsg84 could you please confirm is this would fix the problem?

**Comment by smithsg84** [comment]
The Type should be "PFBFile" not lower case "file".    It is case sensitive.  Does that help?

The pf-keys definitions are used by the Python interface.    There is no central repository of key names in the simulator code itself, each module defines it's keys.    Unfortunately finding them is not super easy.

cd pfsimulator/parflow_lib
grep Porosity.Type *

Show this key is in problem_porosity.c

There is a pattern where we use a "NameArray" to do the switching on keys that can take multiple values.   The switch for the Porosity.Type is using a switch array with two options NA_NewNameArray("Constant PFBFile")

https://github.com/parflow/parflow/blob/e74fbefe88ea64315f10f21da108ccf835dc0314/pfsimulator/parflow_lib/problem_porosity.c#L316

And the converstion of the string to an integer value for use in the C switch is 

https://github.com/parflow/parflow/blob/e74fbefe88ea64315f10f21da108ccf835dc0314/pfsimulator/parflow_lib/problem_porosity.c#L350

**Comment by jsacerot** [comment]
@smithsg84 Thank you for your help. The typo in ```.Type "PFBFile"``` fixed the issue with Porosity. However, another issue was generated with Mannings:

```
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

Is ParFlow expecting a 3D or a 2D grid with the Manning's values?

**Comment by smithsg84** [comment]
It is a 2D grid.    I don't see a test case that uses file input for Mannings so we might have a bug.   Where you providing a 3D file?

@reedmaxwell  I think this points out a broader issue, we don't clearly indicate 2D/3D in the manual for the file reading .   Mannings documentation is a bit inconsistent, the Constant is said to be assigned to all points in the geometries but the Mannings file is a 2D file.   We probably do that for the other surface properties with Constant/File input.    So for clarity I think the manual should say we use the Constant to set values on the top of the domain if the point lies in the geometry (or something like that) and say the file is should be 2D.   And also should probably indicated cell centered (and for other values indicate other location info).   Oh and output should have same documentation updates.    Internally we sometimes use 3D data representation for storage of the surface only properties but I think that is an implementation detail that will confuse users.

**Comment by jsacerot** [comment]
@smithsg84 I was providing a 3D file. The segmentation fault issue is not generated anymore after replacing the input file with a 2D grid. Thank you.

I also consider that the documentation is inconsistent and, in some cases, confusing. Please let me know if I can help update some information in the manual. I would be more than happy to volunteer.

**Comment by smithsg84** [comment]
The error checking on values has been updated to help with values that take one of several options, the error should include the valid values, for example in the Mannings type case:

```
Node 0: Error: invalid type for key <Mannings.Type>
Node 0: Allowed value are:
Node 0: Constant
Node 0: PredefinedFunction
Node 0: PFBFile
```
This should help with minor typo issues.

**Comment by jsacerot** [comment]
That will be very helpful for any user during model development. Thank you so much, @smithsg84! 
I will generate additional pull requests for documentation improvement. Something that called my attention is that there's no information about the ParFlow output files. I think that section is crucial to identify issues in the model and assess performance.
