### ISSUE TITLE
Unclear outputs when using DumpInterval != 1 in PFv3.11

### ISSUE THREAD

**Issue by jsacerot** [parflow/parflow#425]
I want to use DumpInterval to print outputs every 5 timesteps for a simulation that goes from 0 to 10. The number of printed files is correct but the naming is a bit confusing.  

Here is my timing information:
```
#-----------------------------------------------------------------------------
# Setup Simulation Timing [d] (based on input variable units)
#-----------------------------------------------------------------------------
pfset TimingInfo.BaseUnit                                                  1.0    ; # [no default] Base unit of time for entering time values ~ allow time to be discretized on some interval
pfset TimingInfo.StartCount                                                  0    ; # [no default] 0 : advection begins with given initial conditions ; 1 : restart from previous checkpoint
pfset TimingInfo.StartTime                                                   0    ; # [no default] Starting time for the simulation
pfset TimingInfo.StopTime                                                   10    ; # [no default] Stopping time for the simulation
pfset TimingInfo.DumpInterval                                                5    ; # [no default] real time interval at which time-dependent output should be written
#pfset TimingInfo.DumpInterval                                               -5    ; # [no default] real time interval at which time-dependent output should be written
pfset TimeStep.Type                                                 "Constant"    ; # [no default] Constant or Growth (requires additional input keys)
pfset TimeStep.Value                                                       1.0    ; # [no default] used only if a constant time step is selected and indicates the value of the time step for all steps taken
```

Here are the printed output files for pressure:
```
Spinup_Stage1.out.press.00000.pfb
Spinup_Stage1.out.press.00001.pfb
Spinup_Stage1.out.press.00002.pfb
```
Is DumpInterval not supposed to print pressures at time steps 0, 5, and 10, and name the files likewise? or is it accumulating/averaging the results and naming the output files in the new (StopTime-StartTime)/DumbInterval time scale?

Thanks!

**Comment by reedmaxwell** [comment]
The dump interval refers to the simulation time at which output is written; positive values are in units of time, negative values are in intervals of timestep. The output numbers are sequential and relate to the simulation times via the DumpInterval.

You can refer to the [manual section on timing](https://parflow.readthedocs.io/en/latest/keys.html#timing-information), and this is covered in the [short course material ](https://github.com/hydroframe/parflow_python_shortcourse)a bit in the slides [here](https://github.com/hydroframe/parflow_python_shortcourse/blob/main/slides/3.Interacting%20withParflow.pdf).

**Comment by jsacerot** [comment]
@reedmaxwell Thank you for your prompt reply. Could you please provide an example of what you just described? It is still not very clear the difference to me. I ran tests setting ```DumpInterval``` to 5 and -5 and the result is the same. Three files named 00, 01, and 02., were generated.

I also do not find very intuitive the key description in the manual:
```
double TimingInfo.DumpInterval no default This key is the real time interval at which time-dependent output should
be written. A value of 0 will produce undefined behavior. If the value is negative, output will be dumped out every 𝑛
time steps, where 𝑛 is the absolute value of the integer part of the value.
```

Thanks!

**Comment by jsacerot** [comment]
@reedmaxwell @smithsg84 DumpInterval is not working properly in PFv3.11. See below two examples setting ```DumpInterval``` to 5 and -5.

Example 1
---
Timing setup:
```
#-----------------------------------------------------------------------------
# Setup Simulation Timing [d] (based on input variable units)
#-----------------------------------------------------------------------------
pfset TimingInfo.BaseUnit                                                  1.0    ; # [no default] Base unit of time for entering time values ~ allow time to be discretized on some interval
pfset TimingInfo.StartCount                                                  0    ; # [no default] 0 : advection begins with given initial conditions ; >0 : restart from previous checkpoint
pfset TimingInfo.StartTime                                                   0    ; # [no default] Starting time for the simulation
pfset TimingInfo.StopTime                                                   20    ; # [no default] Stopping time for the simulation
pfset TimingInfo.DumpInterval                                                5    ; # [no default] real time interval at which time-dependent output should be written
pfset TimeStep.Type                                                 "Constant"    ; # [no default] Constant or Growth (requires additional input keys)
pfset TimeStep.Value                                                       1.0    ; # [no default] used only if a constant time step is selected and indicates the value of the time step for all steps taken
```
Results:
![image](https://user-images.githubusercontent.com/57607681/199845484-94f320fa-a52e-4307-9725-bf195f102f06.png)

Example 2
---
Timing setup:
```
#-----------------------------------------------------------------------------
# Setup Simulation Timing [d] (based on input variable units)
#-----------------------------------------------------------------------------
pfset TimingInfo.BaseUnit                                                  1.0    ; # [no default] Base unit of time for entering time values ~ allow time to be discretized on some interval
pfset TimingInfo.StartCount                                                  0    ; # [no default] 0 : advection begins with given initial conditions ; >0 : restart from previous checkpoint
pfset TimingInfo.StartTime                                                   0    ; # [no default] Starting time for the simulation
pfset TimingInfo.StopTime                                                   20    ; # [no default] Stopping time for the simulation
pfset TimingInfo.DumpInterval                                               -5    ; # [no default] real time interval at which time-dependent output should be written
pfset TimeStep.Type                                                 "Constant"    ; # [no default] Constant or Growth (requires additional input keys)
pfset TimeStep.Value                                                       1.0    ; # [no default] used only if a constant time step is selected and indicates the value of the time step for all steps taken
```
Results:
![image](https://user-images.githubusercontent.com/57607681/199845590-71a7b79d-59e2-450a-8c60-cb41b48c8382.png)

---
According to the Manual examples for the [timing information](https://parflow.readthedocs.io/en/latest/keys.html#timing-information):

```
#-----------------------------------------------------------------------------
# Setup timing info [hr]
# 8760 hours in a year. Dumping files every 24 hours. Hourly timestep
#-----------------------------------------------------------------------------
pfset TimingInfo.BaseUnit            1.0
pfset TimingInfo.StartCount               0
pfset TimingInfo.StartTime                   0.0
pfset TimingInfo.StopTime            8760.0
pfset TimingInfo.DumpInterval     -24

## Timing constant example
pfset TimeStep.Type                             "Constant"
pfset TimeStep.Value                            1.0

```
If ```DumpInterval``` is negative, outputs should be printed every ``DumpInterval``` timesteps. for my example, it should be at timesteps 0, 5, 10, 15, and 20. Why is PF labeling the files as 0, 1, 2, 3, and 4?

**Comment by reedmaxwell** [comment]
Sorry, I'm not following.  The DumpInterval looks correct here?  Perhaps you might want to look at the short course material, the metadata or the <runname>.out.log file which lists the time steps solved and the output files written?  I think your expectation that the timestamp is in the output file name is possibly part of your confusion.  The output files are sequential.

**Comment by smithsg84** [comment]
The negative dump interval method dumps and 0 and 1 and then starts dumping every Nth timestep.   I don't recall the exact reasons for this but likely related to wanting to capture initial condition at 0 and then the solves.    I'm not sure about changing it since that could impact users expecting this behavior.

**Comment by jsacerot** [comment]
@smithsg84 thank you for your reply. If the results are correct, I think what is needed is just a better description in the manual. It is very confusing because it does not mention that negative ```DumpInterval``` values consider all the time steps evaluated by the solver to print (dump) the results, while setting it to positive values does not (only considers multiples of the timestep defined by the user).
