### ISSUE TITLE
Issue assigning pressure boundary condition to patch using PressureFile and DirEquilRefPatch | ParFlow v3.11

### ISSUE THREAD

**Issue by jsacerot** [parflow/parflow#446]
I am trying to impose a boundary condition on the western side of my box domain using ```DirEquilRefPatch``` and ```DirEquilRefPatch``` as the patch BCPressure type:

Test 1:
---
```
pfset Patch.x-lower.BCPressure.Type		                "PressureFile"
pfset Patch.x-lower.BCPressure.Cycle		                    "Constant"
pfset Patch.x-lower.BCPressure.Alltime.FileName                              \
                                   $env(INPUT_DIR)/wt3K_P.out.press.111690.pfb
```

Test 2:
---
```
pfset Patch.x-lower.BCPressure.Type		            "DirEquilRefPatch"
pfset Patch.x-lower.BCPressure.Cycle		                    "Constant"
pfset Patch.x-lower.BCPressure.RefGeom                                "domain"
pfset Patch.x-lower.BCPressure.RefPatch                              "z-lower"
pfset Patch.x-lower.BCPressure.Alltime.Value                            3468.7
```

After running multiple simulations for both tests, I do not see the imposed boundary condition values in the desired patch. 
- Is there a way of verifying what ParFlow is reading in/setting?
Note that I use a PFB file to define the initial pressure via the ```Geom.domain.ICPressure.FileName``` key.  
- Is there any chance that the initial pressure conditions are overwriting the boundary conditions? or am I missing something in the model setup?

Thank you!

**Comment by reedmaxwell** [comment]
Hi-

ParFlow is a cell-centered model and as such the values for pressure head you are seeing is calculated at the center of the cell.  To be consistent, boundary conditions are imposed at the *edges* of the cell and are 1/2*delta_x (y, or z) from the cell center using the appropriate flux relationship (e.g. Darcy, with relperm terms if unsaturated).  You can read Carol's paper on the stencil formulation Jones and Woodward [2001](https://www.sciencedirect.com/science/article/pii/S0309170800000750?via%3Dihub) or my paper on the TFG e.g. Fig 1 [Maxwell 2013](https://www.sciencedirect.com/science/article/pii/S0309170812002564).  You will also note in these two papers that the fluxes are formulated at cell-interfaces and not cell centers as is consistent with a mass-conservative solution of the mixed form e.g. [Celia et al 1990](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/WR026i007p01483) which of course results in the number of fluxes being one greater than the number of cell-centers in the primary direction of the flux.  This is, I think, the answer to [447](https://github.com/parflow/parflow/issues/447).

I appreciate your enthusiasm for ParFlow and it sounds like you have a lot of questions while learning the basics of hydrologic / subsurface flow modeling.  Please note that we have a [Google Group](https://groups.google.com/g/parflow) for user questions and a lot of archived short course material on GitHub [e.g. the most recent one linked here](https://github.com/hydroframe/ParFlow_Short_Course).  The ParFlow user group might be a more appropriate place to pose your modeling questions, and I think you might benefit from taking a short course or even a more introductory course on numerical methods for groundwater-type problems.  For example, Eileen has all the material for her last GW modeling class [still posted](https://inside.mines.edu/~epoeter/583CSM/index.shtml) and this is a great resource for the basics.

hope this helps

Reed
Princeton University
[Maxwell Integrated Hydrology Lab](http://maxwell.princeton.edu)

**Comment by jsacerot** [comment]
Good morning @reedmaxwell. Thank you for your prompt reply. My apologies for the inconvenience caused by using this platform to confirm some details about the model. I am a MODFLOW modeler transitioning to ParFlow. Many questions have arisen as, in my opinion, ParFlow's manual leaves loose ends, makings its use confusing sometimes.

Could you please tell me how to double-check that the boundary conditions are correctly implemented as desired? 
I have looked at my output pressures and velocities, and they seem not to follow the constraints I am imposing as boundary conditions (PressureFile, DirEquilRefPatch, FluxConst).

Note: I'll post this question in the Google Group to ensure we are on the same page.

Best,

Juan

**Comment by jsacerot** [comment]
@reedmaxwell @smithsg84; Based on your comments and suggestions, we decided to perform several tests using a simplified version of the ```default_richards.tcl``` test. We imposed an initial pressure head of 3 L and boundary conditions on the left (5 L) and right (3 L) patches of the domain using ```DirEquilRefPatch```. Additionally, we considered variable DZ and terrain-following grid. For the latter, the results indicate that boundary conditions might not be appropriately imposed.

This is the timing setup for all the tests:
```
pfset TimingInfo.BaseUnit                                          1
pfset TimingInfo.StartCount                                        0 
pfset TimingInfo.StartTime                                         0
pfset TimingInfo.StopTime                                        200
pfset TimingInfo.DumpInterval                                     -1
pfset TimeStep.Type                                       "Constant"
pfset TimeStep.Value                                               1
```

Here are the resulting pressure heads for the initial time step and the time step at which the values stop changing:

Test 1: Orthogonal grid + constant DZ
---
TCL: [modified_richards.zip](https://github.com/parflow/parflow/files/10405629/modified_richards.zip)

![PH_FP_t00](https://user-images.githubusercontent.com/57607681/212161442-173dee25-7770-4986-99fa-42c8e7daf36e.png)

![PH_FP_t03](https://user-images.githubusercontent.com/57607681/212161498-69ea2060-d3c4-4828-8efd-1d105c2af8f1.png)

Results seem correct.

---
Test 2: Orthogonal grid + variable DZ
---
TCL:  [modified_richards.zip](https://github.com/parflow/parflow/files/10405628/modified_richards.zip)

![PH_FP_t00](https://user-images.githubusercontent.com/57607681/212161879-3a1357ea-799a-47b0-99c1-f0fbbec67106.png)

![PH_FP_t03](https://user-images.githubusercontent.com/57607681/212161952-6736da0b-63b3-4bd0-9bfe-e0a11802ea01.png)

Results seem correct.

---
Test 3: Terrain-following grid + variable DZ
---
TCL: [modified_richards.zip](https://github.com/parflow/parflow/files/10405625/modified_richards.zip)

![PH_FP_t00](https://user-images.githubusercontent.com/57607681/212162098-381f329e-3da7-4f66-8645-35a7976fb422.png)

![PH_FP_t05](https://user-images.githubusercontent.com/57607681/212162156-61e2f040-6e17-4ae7-aa83-88743dd164a2.png)

![PH_FP_t200](https://user-images.githubusercontent.com/57607681/212169568-fbda450a-904d-4dec-b111-2bc5659e2f97.png)

Results do not seem to be correct using the terrain-following grid. The cell on the left bottom should have a value close to 4, while the right bottom cell should have a value close to 2.

---

Could you please provide some feedback on this?

**Comment by rlsandovalp** [comment]
Did you find the cause of the problem? I'm curious because I'm using TFG and var_dz.
