### ISSUE TITLE
parallel netcdf not working!

### ISSUE THREAD

**Issue by xy124** [parflow/parflow#49]
Am I the only one or are you also getting different outputs depending if you run the netcdf on one core (1 1 1) or on multiple cores (3 2 1) ?

The outputs for one core seems right. Please fix this @kulkarni1  ?

**Comment by kulkarni1** [comment]
Theoretically that should not happen at all. What exactly is different? Are the values completely different?
Do you have CDO (climate data operator) tool installed on your machine.
Tell me the output of following
cdo diff run1 run2

**Comment by kulkarni1** [comment]
I just ran the Little Washita configuration (1,1,1) and (3,2,1) and checked the differences in two files. Almost all the values are zeros and in few places the values differ in the order of e-14 or e-15 which may be negligible. However this is not a netcdf issue as it only puts the data in a file and does not manipulate in any other way. So I suppose there is nothing to fix from my side in this regard.

**Comment by xy124** [comment]
please have a look into `test/default_richards_with_netcdf.tcl` 
- there the grid is set statically to `1 1 1`. run it --> the output nc-files are looking nice in VisIt
- change the grid definition within the `tcl`-file to `3 2 1` and run it -->  the output nc-files are looking not correct at all in VisIt

**Comment by kulkarni1** [comment]
I think something may be wrong in your setup. I just ran default richards with 1 1 1 and 3 2 1 configuration and I do not see any significant changes in output. As I said previously, netCDF interface is not manipulating data in anyway before writing it. Have a look at the code. You can see that I am not changing anything with the data. I am attaching two netcdf files which contain differences between two runs. Have a look at the netcdf global attributes in this file to see which command I have used.
https://fz-juelich.sciebo.de/index.php/s/BE90KrbiHdKJLNu
https://fz-juelich.sciebo.de/index.php/s/DV1eLGCnDzXYaRH

**Comment by xy124** [comment]
I investigated further into this and also did a clean install of all dependencies on one of our servers with the following results:

- on the server with the clean results a parallel run of default_richards_with_netcdf.tcl works fine.
- on my local machine with a fresh compiled master version (a55dcde5bb05ef21831261fb38a17bc2f7a2fc89) that is not the case.

I believe basile hector has had a simular issue once. I will ask him when I'm back in France

**Comment by xy124** [comment]
Did the test again with the latest parflow version and the bug is gone. Unfortunately I cannot say what exactly fixed it.

**Comment by kulkarni1** [comment]
What was the HDF5 library version for the previously where the issue occurred?
