### ISSUE TITLE
Error in write_pfb when saving large arrays

### ISSUE THREAD

**Issue by rlsandovalp** [parflow/parflow#510]
Hi all, 

When I try to create large pfb files with 'write_pfb' function I get this error: 

![image](https://github.com/parflow/parflow/assets/51087450/33f365bc-56ac-4713-8855-db74a1d96113)

This only happens when then file size is large. Otherwise, the function works well.

This is what I'm doing:

`aaa = np.ones((7000, 165, 265)).astype(np.float64)`
`write_pfb('PFB/forcing_2009/aaa.pfb', aaa, p=1, q=1, r=1, x=265, y=165, z=7000, dx=2000, dy=2000, dz=1, dist = False)`

Any idea why this happens?

Thanks!

**Comment by smithsg84** [comment]
Thanks for the bug report.

I'm unable to recreate this issue with the following script:

```
import numpy as np
from parflow.tools.io import read_pfb, write_pfb

aaa = np.ones((7000,165, 256)).astype(np.float64)
write_pfb('test.pfb', aaa, p=1, q=1, r=1, x=256, y=165, z=7000, dx=2000, dy=2000, dz=1, dist=False)
```

Looks like the error was on Windows...not sure if that is an issue with the file size.
