### ISSUE TITLE
Porosity PFBFile Option Throwing Error: PFBFile must be one of [Constant]

### ISSUE THREAD

**Issue by michelob23** [parflow/parflow#512]
The "PFBFile" option for Geom.*geometry_name*.Porosity.Type doesn't seem to work. 

With the following keys: 
runname.Geom.Porosity.GeomNames = 'domain'
runname.Geom.domain.Porosity.Type = 'PFBFile'
runname.Geom.domain.Porosity.FileName = 'input/porosity.pfb'

I get the following error:
  Geom:
    domain:
      Porosity:
        Type: PFBFile ^[[91m✘^[[0m
          ^[[93m★^[[0m {'type': 'ERROR', 'message': 'PFBFile must be one of [Constant]'}

I have checked the porosity PFB for any odd values, NaNs etc., and everything looks fine. Thanks in advance.

**Comment by smithsg84** [comment]
Was able to recreate this issue.

Problem in in the Python interface, the TCL interface does not exhibit this bug.

**Comment by MickeyRush** [comment]
Hi Steven, unfortunately I think something is still up with this Porosity PFB business. Even though the ParFlow run finishes successfully, the validation routine is flagging the PFBfile option as an error. Right now I am using the run() method with skip_validation=True to suppress this issue. 

It appears that the validate() method of class EnumDomain() in the file domains.py seems to be flagging the PFBFile option as an error: https://github.com/parflow/parflow/blob/master/pftools/python/parflow/tools/database/domains.py#L219

**Comment by smithsg84** [comment]
I do not see  errors when running the test case.

What is the full error message.

If you installed pypftools with pip did you update the pftools?

When using the non-released development versions using the cmake

 -DPARFLOW_PYTHON_VIRTUAL_ENV=ON

flag will install a "pfpython" script to setup a python env that uses the Python pftools that is from the development branch.

Steve


________________________________

**Comment by MickeyRush** [comment]
Hi Steven, this was my bad – looks like I hadn't updated pftools properly. I've got it working, thank you!
