### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by hmandela** [parflow/parflow#515]
This error presented in the screenshot could be related to what?
![Capture d’écran du 2024-04-17 16-35-08](https://github.com/parflow/parflow/assets/33883241/4ab89064-f719-471e-abf1-a424e923fef7)

**Comment by smithsg84** [comment]
Sorry you are having problems.

Can you build with debugging turned on, this show which code lines are associated with the failure and help track down the problem.   Add the following to the cmake configuration:
                  -DCMAKE_BUILD_TYPE=Debug
                  
and rerun the failing setup.    The error should then show us the code file/line rather than just the hex addresses.

**Comment by hmandela** [comment]
Okay, I will do it, and you will come back. Thx very much.

**Comment by hmandela** [comment]
![Capture d’écran du 2024-04-23 10-56-03](https://github.com/parflow/parflow/assets/33883241/98500852-b994-4a1f-8e5a-9ee682f10158)

After recompiling with the debug option activated, I tried several times to execute, but I still encounter this error. Perhaps I could share my simulation folder with you. Furthermore, I am simulating with the IGE-CLM branch.

**Comment by hmandela** [comment]
Here is the implicated part in clm.F90:

           ! reset node depths (clm%z) based on variable dz multiplier
           do k = 1, nlevsoi
              l                 = 1+i + j_incr*(j) + k_incr*(clm(t)%topo_mask(1)-(k-1))
	          clm(t)%dz(k)	= drv%dz * pf_dz_mult(l) ! basile
              if (k==1) then
                 clm(t)%z(k)    = 0.5 * drv%dz * pf_dz_mult(l)
	      	clm(t)%zi(k)	= drv%dz * pf_dz_mult(l) ! basile
              else
                 total          = 0.0
                 do k1 = 1, k-1
                    l1          = 1+i + j_incr*(j) + k_incr*(clm(t)%topo_mask(1)-(k1-1))
                    total       = total + (drv%dz * pf_dz_mult(l1))
                 enddo
                 clm(t)%z(k)       = total + (0.5 * drv%dz * pf_dz_mult(l))
		clm(t)%zi(k)	= total + drv%dz * pf_dz_mult(l)! basile
 
              endif
    
           enddo
