### ISSUE TITLE
Coding guidelines

### ISSUE THREAD

**Issue by xy124** [parflow/parflow#63]
Hi,
I'm about to add *parflow as a FlowVR module* functionality to parflow. Unfortunately it is not very clear to me which coding guidelines (concerning for example upper/smaller case functionnames / varnames...) should be used and if the PFModule approach is still recent (I have seen some newer modules like the netcdf-writer that are not using it and atm I'm also not using it for my modules at it seems too complicated)

What do you think is the way to go?

Can you please link a code guideline telling me how to name my variable and function names?

Maybe a Contributing section might be cool in the readme.

(@smithsg84 - I'm linking you as I guess you might give me an answer )

**Comment by smithsg84** [comment]
Sorry for late response, been on vacation.

Yes it would be good to have better contributor documentation.   

In general I believe the most common style is to use Camel case for external function names and structure typedef's.   lower case with "_" separator is used for variable names.

The coding guidelines are sparse and not very current; we don't seem to have documented function names style anywhere.    Existing documentation is in the pftools/docs directory.   I'm intending on moving that to the root directory shortly so it is a bit more obvious.   A recent checkout will build PDF versions of the user and developers manuals under cmake if "-DPARFLOW_ENABLE_LATEX=TRUE" is specified for the cmake build.  The developer manual is really out of date but has some description of the module system.

The PF module system was designed to enable simple polymorphism in C (ParFlow was started before C++ was commonly available).   A PFModule is basically a simply hand-coded object system.   It is used where we want to allow a choice of algorithms (like the solver).  Until we move to C++ we plan to keep using it.   PF module might not be needed for your additions.

Actually the I/O is a good example of what we were trying to avoid, all those replicated if/switch blocks.   I was thinking it would clean things up if we had used modules for the I/O selection.

Hope that helps.

**Comment by xy124** [comment]
Thank you, it helps a lot. I will merge in the latest changes from master to test the LATEX-cmake switch.

Using C++ would probably really be a great idea as it would simplify the code in many places and with the template system high performance can be reached
