### ISSUE TITLE
cmake module name: netCDF <-> NetCDF

### ISSUE THREAD

**Issue by xy124** [parflow/parflow#64]
I compiled netcdf from scratch and on my distribution the cmake netcdf module is named **netCDF** and not NetCDF.
In the current version the pr https://github.com/parflow/parflow/pull/52/files is reverted and thus I cannot compile with netcdf support:
https://github.com/parflow/parflow/blob/d92b1142f09fafb66858d8a29d441291d09b768b/CMakeLists.txt#L105

to test:
- compile with cmake and activated NetCDF option
-  then run:
```bash
cd test
make testclean
tclsh default_richards_with_netcdf.tcl
```

Is it just my distribution where the netCDF module is named like this or do you have the same error?

**Comment by smithsg84** [comment]
Yes the lower case netCDF was breaking builds.   The cmake module is named FindNetCDF.cmake. File is in the local modules directory:

parflow/cmake/modules/FindNetCDF.cmake

what platform and cmake version are you using?   Maybe we are getting a conflict?

**Comment by xy124** [comment]
I'm getting my netcdf directly from the github. for installing it I use the following:
```bash
git clone https://github.com/Unidata/netcdf-c --depth 1
cd netcdf-c/
mkdir build
cd build/
cmake .. -DBUILD_SHARED_LIBS:BOOL=OFF \
  -DBUILD_TESTING:BOOL=ON \
  -DBUILD_TESTSETS:BOOL=ON \
  -DBUILD_UTILITIES:BOOL=ON \
  -DCMAKE_BUILD_TYPE:STRING=RELEASE \
  -DCMAKE_C_COMPILER:FILEPATH=$MPICC \
  -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX \
  -DENABLE_CDF5:BOOL=ON \
  -DENABLE_CONVERSION_WARNINGS:BOOL=ON \
  -DENABLE_COVERAGE_TESTS:BOOL=OFF \
  -DENABLE_DAP:BOOL=ON \
  -DENABLE_DAP2:BOOL=ON \
  -DENABLE_DAP4:BOOL=ON \
  -DENABLE_DAP_GROUPS:BOOL=ON \
  -DENABLE_DAP_LONG_TESTS:BOOL=OFF \
  -DENABLE_DAP_REMOTE_TESTS:BOOL=ON \
  -DENABLE_DISKLESS:BOOL=ON \
  -DENABLE_DOXYGEN:BOOL=OFF \
  -DENABLE_DYNAMIC_LOADING:BOOL=ON \
  -DENABLE_ERANGE_FILL:BOOL=OFF \
  -DENABLE_EXAMPLES:BOOL=ON \
  -DENABLE_EXAMPLE_TESTS:BOOL=OFF \
  -DENABLE_EXTRA_TESTS:BOOL=OFF \
  -DENABLE_EXTREME_NUMBERS:BOOL=ON \
  -DENABLE_FAILING_TESTS:BOOL=OFF \
  -DENABLE_FFIO:BOOL=OFF \
  -DENABLE_FSYNC:BOOL=OFF \
  -DENABLE_HDF4:BOOL=OFF \
  -DENABLE_JNA:BOOL=OFF \
  -DENABLE_LARGE_FILE_SUPPORT:BOOL=ON \
  -DENABLE_LARGE_FILE_TESTS:BOOL=OFF \
  -DENABLE_LOGGING:BOOL=OFF \
  -DENABLE_MMAP:BOOL=ON \
  -DENABLE_NETCDF4:BOOL=ON \
  -DENABLE_NETCDF_4:BOOL=ON \
  -DENABLE_PARALLEL4:BOOL=ON \
  -DENABLE_PARALLEL_TESTS:BOOL=ON \
  -DENABLE_PNETCDF:BOOL=ON \
  -DENABLE_REMOTE_FORTRAN_BOOTSTRAP:BOOL=OFF \
  -DENABLE_RPC:BOOL=OFF \
  -DENABLE_SHARED_LIBRARY_VERSION:BOOL=ON \
  -DENABLE_STDIO:BOOL=OFF \
  -DENABLE_TESTS:BOOL=ON \
  -DENABLE_V2_API:BOOL=ON \
  -DENABLE_ZERO_LENGTH_COORD_BOUND:BOOL=OFF \
  -DPNETCDF:FILEPATH=$PREFIX/lib/libpnetcdf.a \
  -DPNETCDF_INCLUDE_DIR:PATH=$PREFIX/include \
  -DTEST_PARALLEL:BOOL=ON \
  -DTEST_PARALLEL4:BOOL=ON \
  -DUSE_CDF5:BOOL=ON \
  -DUSE_DAP:BOOL=ON \
  -DUSE_HDF5:BOOL=ON \
  -DUSE_LIBDL:BOOL=ON \
  -DUSE_NETCDF4:BOOL=ON \
  -DUSE_PARALLEL:BOOL=ON \
  -DUSE_PNETCDF:BOOL=ON


  make -j$N && make install -j$N
```

I know that I still compile with PNETCDF what I shouldn't but I did not manage to get it working without.
Maybe you can tell me the exact steps you use for building?

**Comment by kulkarni1** [comment]
Perhaps following might be useful.
https://www.unidata.ucar.edu/software/netcdf/docs/getting_and_building_netcdf.html#build_parallel

**Comment by xy124** [comment]
@kulkarni1 Thanks! That gave me the idea of rebuilding netcdf with the configure ... guess what: it worked (at least on my local machine)

The following command did the trick of building netcdf:
```bash
CC=/usr/bin/mpicc ./configure --enable-parallel --prefix=$PREFIX
make -j$N && make install -j$N
```
I will keep testing ;)
