### ISSUE TITLE
The -DMPIEXEC flag doesn't seem to work

### ISSUE THREAD

**Issue by cozisco** [parflow/parflow#72]
I imagine I'm not alone, but I had trouble when CMake tried to determine the appropriate MPI launcher. Namely, I had to change the launcher from the absolute path name to the general command** and include the `--oversubscribe` option. To fix it, I had to manually edit the parflow/config/pf-cmake-env.sh file because the `-DMPIEXEC` flag (README-CMAKE.md, line 199) didn't seem to do anything. Is that flag operational? I noticed that it isn't listed in the CMake GUI.

**For me, CMake correctly identifies the executable for running MPI programs (/bin/mpiexec), but it replaces the `$MPIEXEC` variable with the absolute path (/bin/mpiexec) rather than the command (mpiexec). Calling OpenMPI with the absolute pathname is equivalent to using the [--prefix option](https://www.open-mpi.org/faq/?category=running#mpirun-prefix) and thus results in a series of errors, since there is no prefix to /bin/mpiexec.

**Comment by xy124** [comment]
You can see it in cmake GUI (`ccmake`) by hitting `t` to toggle advanced mode.

I have a working setup using
```
cmake [...] -DMPIEXEC=/usr/bin/mpiexec
```
but normally if you do not set MPIEXEC at all it finds it automatically, starting to search in your set up
`CMAKE_INSTALL_PREFIX` ...

**Comment by smithsg84** [comment]
Using -DMPIEXEC=<command> on the cmake line also works for me.   When I add a `-DMPIEXEC=srun` the resulting pf-cmake-env.sh file has the command correctly recorded:

`MPIEXEC=srun`

Regarding the fully qualified path that is being found, the default behaviour in CMAKE is to find programs with a fully qualified path on them.  I don't think we should manually strip off the path in ParFlow usage since that will likely confuse users who are expecting the default behavior.

**Comment by smithsg84** [comment]
I had forgotten about this.   When using the ParFlow run script the environment variable PARFLOW_MPIEXEC_EXTRA_FLAGS  can be used to add arguments to the MPI execution command.  For example when running with OpenMPI on a single workstation the following will enable running more MPI tasks than cores and disable the busy loop waiting to improve performance:

`export PARFLOW_MPIEXEC_EXTRA_FLAGS="--mca mpi_yield_when_idle 1 --oversubscribe"`

**Comment by cozisco** [comment]
That's perfect, thank you. I hadn't seen it, but PARFLOW_MPIEXEC_EXTRA_FLAGS works great.
