### ISSUE TITLE
Warning/Error message when using git clone

### ISSUE THREAD

**Issue by prabshr** [parflow/parflow#74]
error: gnutls_handshake() failed: A TLS fatal alert has been received. while accessing https://github.com/parflow/parflow.git/info/refs
-bash: syntax error near unexpected token `('

**Comment by kulkarni1** [comment]
Please upgrade your git client.
GitHub.com no longer supports git over dumb-http: https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days

**Comment by prabshr** [comment]
The articles says it was turned off around 2011, but I did not have such
problems couple of months ago...
but anway will check with the MIUB IT

**Comment by smithsg84** [comment]
Closing issue as this doesn't appear to be Parflow specific.
If this is still a problem please re-open.
