### ISSUE TITLE
CMAKE configure system

### ISSUE THREAD

**Issue by smithsg84** [parflow/parflow#9]
The current Parflow build system is old (some of the macros are 20+ years old) and is brittle.   It is time to clean things up.   

There are two main options being considered:

1. Bring autoconf system up-to-date.
  a. Use autoconf macros from libraries rather than custom ones when possible.
  b. Update custom macros to current autoconf designs and patterns

2. Replace autoconf with CMake

The CMake option is currently the leading choice due to the greater platform independence and ability to generate IDE configuration files.   While this isn't highly relevant for the large HPC, machines it would make it easier for some contributors to use their favorite development tools.

This issue is being opened to see if there is another option that Parflow community feels should be considered and allow comments on autoconf vs CMake.

Chime if you have any strong feelings.

Steve

**Comment by kgoergen** [comment]
From the Juelich/Bonn side, we would opt for a cmake-based solution.

Klaus

**Comment by smithsg84** [comment]
CMake build system rework has been started here:

git@github.com:smithsg84/parflow.git

**Comment by smithsg84** [comment]
- [ ] Basic CMake setup
- [ ] Convert test framekwork to Ctest
- [ ] Complete converting all autoconf configure options/system probes over to CMake
- [ ] Test system on multiple platforms

**Comment by oseikuffuor1** [comment]
I successfully performed a basic sequential installation of ParFlow on my office linux tux box running RHEL 6.9 with gcc 4.4.7 and on my Mac running MacOS 10.12.5 (sierra)  with LLVM version 6.1.0 (clang-602.0.53). The instructions in the README-CMAKE file were pretty straightforward and I did not have to do much to get it to work. On my tux box, I needed to make sure I had both the TCL and the TCL-dev libraries installed.

I was able to do a 'make test' to run the test examples. However, a few of the sequential tests failed. I will review the files later to see if I can provide more information about the cause of these failures. I encourage others to attempt their own cmake builds of ParFlow and provide feedback, so we know if the build system is working well.

**Comment by kulkarni1** [comment]
I tested CMake branch on our general purpose linux cluster JURECA with Cmake version 3.7.2 and intel 2017 C anf fortran compilers with parastation MPI. I followed the instructions in README-CMAKE.md and the model compiles as expected.  default_single.tcl test passed.
I tried running Little Washita test case and it failed with following error
**Node 0: Error: can't open input file ../../NLDAS//NLDAS.DSWR.000001_to_000024.pfb**
But this file is present. Another case is by default sequential IO is disabled. Whenever I try to compile with -DPARFLOW_AMPS_SEQUENTIAL_IO=TRUE I do not see a shared binary output for above mentioned test case. May be I am missing something. But compilation works as instructed.

**Comment by smithsg84** [comment]
The cmake branch was merged with master.   The cmake support is still beta as we test on multiple platforms and work out remaining issues.   Since the CMake support is operating in parallel with autoconf this should not cause any issues.

The TravisCI test will build both the GNU Autoconf and CMake versions until we deprecate autoconf support.

**Comment by smithsg84** [comment]
All major features have been added to CMake configure scripts.

SAMRAI not added as it has not been tested in many years.   An issue will be opened for adding/testing SAMRAI support.
